/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkinboostersRouteImport } from './routes/skinboosters'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrpRouteImport } from './routes/prp'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LaserFotonaRouteImport } from './routes/laser-fotona'
import { Route as IntimateRejuvenationRouteImport } from './routes/intimate-rejuvenation'
import { Route as InjectionsAcideHyaluroniqueRouteImport } from './routes/injections-acide-hyaluronique'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BodyContouringRouteImport } from './routes/body-contouring'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BiostimulatorsRouteImport } from './routes/biostimulators'
import { Route as AboutDrImanAbdelaalRouteImport } from './routes/about-dr-iman-abdelaal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'

const SkinboostersRoute = SkinboostersRouteImport.update({
  id: '/skinboosters',
  path: '/skinboosters',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrpRoute = PrpRouteImport.update({
  id: '/prp',
  path: '/prp',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LaserFotonaRoute = LaserFotonaRouteImport.update({
  id: '/laser-fotona',
  path: '/laser-fotona',
  getParentRoute: () => rootRouteImport,
} as any)
const IntimateRejuvenationRoute = IntimateRejuvenationRouteImport.update({
  id: '/intimate-rejuvenation',
  path: '/intimate-rejuvenation',
  getParentRoute: () => rootRouteImport,
} as any)
const InjectionsAcideHyaluroniqueRoute =
  InjectionsAcideHyaluroniqueRouteImport.update({
    id: '/injections-acide-hyaluronique',
    path: '/injections-acide-hyaluronique',
    getParentRoute: () => rootRouteImport,
  } as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyContouringRoute = BodyContouringRouteImport.update({
  id: '/body-contouring',
  path: '/body-contouring',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BiostimulatorsRoute = BiostimulatorsRouteImport.update({
  id: '/biostimulators',
  path: '/biostimulators',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDrImanAbdelaalRoute = AboutDrImanAbdelaalRouteImport.update({
  id: '/about-dr-iman-abdelaal',
  path: '/about-dr-iman-abdelaal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-dr-iman-abdelaal': typeof AboutDrImanAbdelaalRoute
  '/biostimulators': typeof BiostimulatorsRoute
  '/blog': typeof BlogRouteWithChildren
  '/body-contouring': typeof BodyContouringRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/injections-acide-hyaluronique': typeof InjectionsAcideHyaluroniqueRoute
  '/intimate-rejuvenation': typeof IntimateRejuvenationRoute
  '/laser-fotona': typeof LaserFotonaRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/prp': typeof PrpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skinboosters': typeof SkinboostersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-dr-iman-abdelaal': typeof AboutDrImanAbdelaalRoute
  '/biostimulators': typeof BiostimulatorsRoute
  '/blog': typeof BlogRouteWithChildren
  '/body-contouring': typeof BodyContouringRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/injections-acide-hyaluronique': typeof InjectionsAcideHyaluroniqueRoute
  '/intimate-rejuvenation': typeof IntimateRejuvenationRoute
  '/laser-fotona': typeof LaserFotonaRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/prp': typeof PrpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skinboosters': typeof SkinboostersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-dr-iman-abdelaal': typeof AboutDrImanAbdelaalRoute
  '/biostimulators': typeof BiostimulatorsRoute
  '/blog': typeof BlogRouteWithChildren
  '/body-contouring': typeof BodyContouringRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/injections-acide-hyaluronique': typeof InjectionsAcideHyaluroniqueRoute
  '/intimate-rejuvenation': typeof IntimateRejuvenationRoute
  '/laser-fotona': typeof LaserFotonaRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/prp': typeof PrpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skinboosters': typeof SkinboostersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-dr-iman-abdelaal'
    | '/biostimulators'
    | '/blog'
    | '/body-contouring'
    | '/contact'
    | '/faq'
    | '/galerie'
    | '/injections-acide-hyaluronique'
    | '/intimate-rejuvenation'
    | '/laser-fotona'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/prp'
    | '/sitemap.xml'
    | '/skinboosters'
    | '/article/$slug'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-dr-iman-abdelaal'
    | '/biostimulators'
    | '/blog'
    | '/body-contouring'
    | '/contact'
    | '/faq'
    | '/galerie'
    | '/injections-acide-hyaluronique'
    | '/intimate-rejuvenation'
    | '/laser-fotona'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/prp'
    | '/sitemap.xml'
    | '/skinboosters'
    | '/article/$slug'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-dr-iman-abdelaal'
    | '/biostimulators'
    | '/blog'
    | '/body-contouring'
    | '/contact'
    | '/faq'
    | '/galerie'
    | '/injections-acide-hyaluronique'
    | '/intimate-rejuvenation'
    | '/laser-fotona'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/prp'
    | '/sitemap.xml'
    | '/skinboosters'
    | '/article/$slug'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutDrImanAbdelaalRoute: typeof AboutDrImanAbdelaalRoute
  BiostimulatorsRoute: typeof BiostimulatorsRoute
  BlogRoute: typeof BlogRouteWithChildren
  BodyContouringRoute: typeof BodyContouringRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalerieRoute: typeof GalerieRoute
  InjectionsAcideHyaluroniqueRoute: typeof InjectionsAcideHyaluroniqueRoute
  IntimateRejuvenationRoute: typeof IntimateRejuvenationRoute
  LaserFotonaRoute: typeof LaserFotonaRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  PrpRoute: typeof PrpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkinboostersRoute: typeof SkinboostersRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skinboosters': {
      id: '/skinboosters'
      path: '/skinboosters'
      fullPath: '/skinboosters'
      preLoaderRoute: typeof SkinboostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prp': {
      id: '/prp'
      path: '/prp'
      fullPath: '/prp'
      preLoaderRoute: typeof PrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laser-fotona': {
      id: '/laser-fotona'
      path: '/laser-fotona'
      fullPath: '/laser-fotona'
      preLoaderRoute: typeof LaserFotonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intimate-rejuvenation': {
      id: '/intimate-rejuvenation'
      path: '/intimate-rejuvenation'
      fullPath: '/intimate-rejuvenation'
      preLoaderRoute: typeof IntimateRejuvenationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/injections-acide-hyaluronique': {
      id: '/injections-acide-hyaluronique'
      path: '/injections-acide-hyaluronique'
      fullPath: '/injections-acide-hyaluronique'
      preLoaderRoute: typeof InjectionsAcideHyaluroniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-contouring': {
      id: '/body-contouring'
      path: '/body-contouring'
      fullPath: '/body-contouring'
      preLoaderRoute: typeof BodyContouringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biostimulators': {
      id: '/biostimulators'
      path: '/biostimulators'
      fullPath: '/biostimulators'
      preLoaderRoute: typeof BiostimulatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-dr-iman-abdelaal': {
      id: '/about-dr-iman-abdelaal'
      path: '/about-dr-iman-abdelaal'
      fullPath: '/about-dr-iman-abdelaal'
      preLoaderRoute: typeof AboutDrImanAbdelaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutDrImanAbdelaalRoute: AboutDrImanAbdelaalRoute,
  BiostimulatorsRoute: BiostimulatorsRoute,
  BlogRoute: BlogRouteWithChildren,
  BodyContouringRoute: BodyContouringRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalerieRoute: GalerieRoute,
  InjectionsAcideHyaluroniqueRoute: InjectionsAcideHyaluroniqueRoute,
  IntimateRejuvenationRoute: IntimateRejuvenationRoute,
  LaserFotonaRoute: LaserFotonaRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  PrpRoute: PrpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkinboostersRoute: SkinboostersRoute,
  ArticleSlugRoute: ArticleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
